GAME OF LIFE: Header.h File Reference
Header.h File Reference
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <Windows.h>
#include <ncurses.h>
Data Structures
struct cell
Macros
#define DEBUG
#define Y 50
#define X 70
#define HOLE 4
#define MUD 3
#define IN_MUD_W 5
#define IN_MUD_Y 6
#define TIME 100
#define FILE_LIVES "life.txt"
#define FILE_LAND "land.txt"
Functions
void zero_the_boards (struct cell board[Y][X])
void first_board (struct cell board[Y][X])
void print_first_board (struct cell board[Y][X])
void check_rules_and_put_to_place (struct cell board[Y][X])
void print_new_board (struct cell board[Y][X])
void read_states (FILE *stream, struct cell board[Y][X])
void read_land_states (FILE *stream_land, struct cell(*board)[X])
void start_game (struct cell board[Y][X])
void save_file (struct cell board[Y][X])
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 49 of file Header.h.
FILE_LAND
#define FILE_LAND "land.txt"
Definition at line 60 of file Header.h.
FILE_LIVES
#define FILE_LIVES "life.txt"
Definition at line 59 of file Header.h.
HOLE
#define HOLE 4
Definition at line 54 of file Header.h.
IN_MUD_W
#define IN_MUD_W 5
Definition at line 56 of file Header.h.
IN_MUD_Y
#define IN_MUD_Y 6
Definition at line 57 of file Header.h.
MUD
#define MUD 3
Definition at line 55 of file Header.h.
TIME
#define TIME 100
Definition at line 58 of file Header.h.
X
#define X 70
Definition at line 53 of file Header.h.
Y
#define Y 50
Definition at line 52 of file Header.h.
Function Documentation
check_rules_and_put_to_place()
void check_rules_and_put_to_place (struct cell board[Y][X])
Definition at line 60 of file check_rules.c.
 {
         int count = 0;
         int count2 = 0;
         int mud_count = 0;
         for (int i = 0; i < Y; i++) {
                 for (int j = 0; j < X; j++) {
                         /********************LASKETAAN YMPÄRISTÖSSÄ OLEVAT ELÄVÄT SOLUT**************************************************/
                         if (board[i][j].current == 1 || board[i][j].current == 2 || board[i][j].current == IN_MUD_W || board[i][j].current == IN_MUD_Y) {
                                 if (board[i][j].land == MUD && board[i][j].current != IN_MUD_W && board[i][j].current != IN_MUD_Y) mud_count++;/*Tarkastetaan onko solu mudassa*/
                                 if (j != X - 1) {
                                         if (board[i][j + 1].current == 1 || board[i][j + 1].current == IN_MUD_W) count++;
                                         else if (board[i][j + 1].current == 2 || board[i][j + 1].current == IN_MUD_Y) count2++;
                                 }
                                 if (j != 0) {
                                         if (board[i][j - 1].current == 1 || board[i][j - 1].current == IN_MUD_W) count++;
                                         else if (board[i][j - 1].current == 2 || board[i][j - 1].current == IN_MUD_Y) count2++;
                                 }
                                 if (i != 0) {
                                         if (board[i - 1][j].current == 1 || board[i - 1][j].current == IN_MUD_W) count++;
                                         else if (board[i - 1][j].current == 2 || board[i - 1][j].current == IN_MUD_Y) count2++;
                                         if (j != 0 && board[i - 1][j - 1].current == 1 || board[i - 1][j - 1].current == IN_MUD_W) count++;
                                         else if (j != 0 && board[i - 1][j - 1].current == 2 || board[i - 1][j - 1].current == IN_MUD_Y) count2++;
                                         if (j != X - 1 && board[i - 1][j + 1].current == 1 || board[i - 1][j + 1].current == IN_MUD_W) count++;
                                         else if (j != X - 1 && board[i - 1][j + 1].current == 2 || board[i - 1][j + 1].current == IN_MUD_Y) count2++;
                                 }
                                 if (i != Y - 1) {
                                         if (board[i + 1][j].current == 1 || board[i + 1][j].current == IN_MUD_W) count++;
                                         else if (board[i + 1][j].current == 2 || board[i + 1][j].current == IN_MUD_Y) count2++;
                                         if (j != 0 && board[i + 1][j - 1].current == 1 || board[i + 1][j - 1].current == IN_MUD_W) count++;
                                         else if (j != 0 && board[i + 1][j - 1].current == 2 || board[i + 1][j - 1].current == IN_MUD_Y) count2++;
                                         if (j != X - 1 && board[i + 1][j + 1].current == 1 || board[i + 1][j + 1].current == IN_MUD_W) count++;
                                         else if (j != X - 1 && board[i + 1][j + 1].current == 2 || board[i + 1][j + 1].current == IN_MUD_Y) count2++;
                                 }
                                 /*********************LAITETAAN UUDET SOLUT PAIKALLEEN****************************************************/
                                 if (board[i][j].land != HOLE && mud_count != 1 ) {/*tarkastetaan että solu ei ole reiässä eikä mudassa*/
                                         if (board[i][j].current == 1 || board[i][j].current == IN_MUD_W) {
                                                 if (count == 1 || count == 0 || count >= 4) {
                                                         board[i][j].future = 0;
                                                 }
                                                 if (count == 2 || count == 3) {
                                                         board[i][j].future = 1;
                                                 }
                                                 if (count2 > count) {
                                                         board[i][j].future = 2;
                                                 }
                                         }
                                         if (board[i][j].current == 2 || board[i][j].current == IN_MUD_Y) {
                                                 if (count2 == 1 || count2 == 0 || count2 >= 4) {
                                                         board[i][j].future = 0;
                                                 }
                                                 if (count2 == 2 || count2 == 3) {
                                                         board[i][j].future = 2;
                                                 }
                                                 if (count > count2) {
                                                         board[i][j].future = 1;
                                                 }
                                         }
                                 }
                                 count = 0;
                                 count2 = 0;
                                 /**************************************/
                         }
                         if (board[i][j].land != HOLE && mud_count != 1 ) {
                                  if (board[i][j].current == 0) {
                                         if (j != X - 1) {
                                                 if (board[i][j + 1].current == 1 || board[i][j + 1].current == IN_MUD_W) count++;
                                                 else if (board[i][j + 1].current == 2 || board[i][j + 1].current == IN_MUD_Y) count2++;
                                         }
                                         if (j != 0) {
                                                 if (board[i][j - 1].current == 1 || board[i][j - 1].current == IN_MUD_W) count++;
                                                 else if (board[i][j - 1].current == 2 || board[i][j - 1].current == IN_MUD_Y) count2++;
                                         }
                                         if (i != 0) {
                                                 if (board[i - 1][j].current == 1 || board[i - 1][j].current == IN_MUD_W) count++;
                                                 else if (board[i - 1][j].current == 2 || board[i - 1][j].current == IN_MUD_Y) count2++;
                                                 if (j != 0 && board[i - 1][j - 1].current == 1 || board[i - 1][j - 1].current == IN_MUD_W) count++;
                                                 else if (j != 0 && board[i - 1][j - 1].current == 2 || board[i - 1][j - 1].current == IN_MUD_Y) count2++;
                                                 if (j != X - 1 && board[i - 1][j + 1].current == 1 || board[i - 1][j + 1].current == IN_MUD_W) count++;
                                                 else if (j != X - 1 && board[i - 1][j + 1].current == 2 || board[i - 1][j + 1].current == IN_MUD_Y) count2++;
                                         }
                                         if (i != Y - 1) {
                                                 if (board[i + 1][j].current == 1 || board[i + 1][j].current == IN_MUD_W) count++;
                                                 else if (board[i + 1][j].current == 2 || board[i + 1][j].current == IN_MUD_Y) count2++;
                                                 if (j != 0 && board[i + 1][j - 1].current == 1 || board[i + 1][j - 1].current == IN_MUD_W) count++;
                                                 else if (j != 0 && board[i + 1][j - 1].current == 2 || board[i + 1][j - 1].current == IN_MUD_Y) count2++;
                                                 if (j != X - 1 && board[i + 1][j + 1].current == 1 || board[i + 1][j + 1].current == IN_MUD_W) count++;
                                                 else if (j != X - 1 && board[i + 1][j + 1].current == 2 || board[i + 1][j + 1].current == IN_MUD_Y) count2++;
                                         }
                                         if (count == 3) {
                                                 board[i][j].future = 1;
                                         }
                                         else if (count2 == 3) {
                                                 board[i][j].future = 2;
                                         }
                                         count = 0;
                                         count2 = 0;
                                         }
                                 }
                         if (board[i][j].land == HOLE) {
                                 board[i][j].future == 0;
                         }
                         if (mud_count == 1 && board[i][j].current == 1) {
                                 board[i][j].future = IN_MUD_W;
                                 mud_count = 0;
                         }
                         else if (mud_count == 1 && board[i][j].current == 2) {
                                 board[i][j].future = IN_MUD_Y;
                                 mud_count = 0;
                         }
                 }
         }
 }
References HOLE, IN_MUD_W, IN_MUD_Y, MUD, X, and Y.
Referenced by main().
first_board()
void first_board (struct cell board[Y][X])
Definition at line 58 of file first_board.c.
 {
         int ran;
         int ran_l;
         int first = X / 2;
         srand(time(0));                 /*luodaan eka siviilisaatio*/
         for (int i = 0; i < Y; i++) {
                 for (int j = 0; j < X; j++) {
                         ran = rand() % 20;
                         ran_l = rand() % 50;
                         if (ran_l == HOLE) {
                                 board[i][j].land = HOLE;
                         }
                         if (ran_l == MUD) {
                                 board[i][j].land = MUD;
                         }
                         if (ran <= 8 && j <= first) {
                                 if (j > first - 3) {
                                         board[i][j - 3].current = 1;
                                 }
                                 else { board[i][j].current = 1; }
                         }
                         if (ran <= 8 && j >= first) {
                                 if (j < first + 3) {
                                         board[i][j + 3].current = 2;
                                 }
                                 else {
                                         board[i][j].current = 2;
                                 }
                         }
                 }
         }
 }
References HOLE, MUD, X, and Y.
Referenced by start_game().
print_first_board()
void print_first_board (struct cell board[Y][X])
Definition at line 58 of file print_first_board.c.
 {
         int row, col;
         getmaxyx(stdscr, row, col);
         int rowm = row / 2 - (Y / 2);
         int colm = col / 2 - (X / 2);
         move(rowm, colm - 2);
         for (int i = 0; i < Y; i++) {/*tulostaa ekan siviilisaation*/
                 move(rowm + i, colm - 2);
                 for (int j = 0; j < X; j++) {
                         if (board[i][j].land == MUD) {
                                 attron(COLOR_PAIR(1));
                         }
                         else if (board[i][j].land == HOLE) {
                                 attron(COLOR_PAIR(2));
                         }
                         else
{
                                 attron(COLOR_PAIR(3));
                         }
                         if (board[i][j].current == 0) {
                                 printw(". ");
                         }
                         else {
                                 if (board[i][j].current == 1) {
                                         attron(COLOR_PAIR(4));
                                 }
                                 if (board[i][j].current == 2) {
                                         attron(COLOR_PAIR(5));
                                 }
                                 printw("%d ", board[i][j].current);
                         }
                         attroff(COLOR_PAIR(2));
                         attroff(COLOR_PAIR(1));
                         attroff(COLOR_PAIR(3));
                         attroff(COLOR_PAIR(4));
                         attroff(COLOR_PAIR(5));
                 }
                 printw("\n");
         }
         refresh();
         Sleep(1000);
         clear();
 }
References cell::current, HOLE, cell::land, MUD, X, and Y.
Referenced by main().
print_new_board()
void print_new_board (struct cell board[Y][X])
Definition at line 59 of file print_new_board.c.
 {
         int row, col;
         WINDOW * win = newwin(4, 27, 1, 1);
         refresh();
         box(win, '*', '*');
         getmaxyx(stdscr, row, col);
         int rowm = row / 2 - (Y / 2);
         int colm = col / 2 - (X / 2);
         move(rowm, colm - 2);
         for (int i = 0; i < Y; i++) {
                 move(rowm + i, colm - 2);
                 for (int j = 0; j < X; j++) {
                         /**********COLORS*********************/
                         board[i][j].current = board[i][j].future;
                         if (board[i][j].land == MUD) {
                                 attron(COLOR_PAIR(1));
                         }
                         else if (board[i][j].land == HOLE) {
                                 attron(COLOR_PAIR(2));
                         }
                         else{
                                 attron(COLOR_PAIR(3));
                         }
                         /****************************************/
                         if (board[i][j].current == 0) {
                                 printw(". ");
                         }
                         if(board[i][j].current == 1 || board[i][j].current == IN_MUD_W) {
                                 attron(COLOR_PAIR(4));
                                 printw("%d ", board[i][j].current);
                         }
                         if (board[i][j].current == 2 || board[i][j].current == IN_MUD_Y) {
                                 attron(COLOR_PAIR(5));
                                 printw("%d ", board[i][j].current);
                         }
                         attroff(COLOR_PAIR(1));
                         attroff(COLOR_PAIR(2));
                         attroff(COLOR_PAIR(3));
                         attroff(COLOR_PAIR(4));
                         attroff(COLOR_PAIR(5));
                 }
                 printw("\n");
         }
         mvwprintw(win, 1, 1, "press any key to stop...");
         wrefresh(win);
         refresh();
         Sleep(TIME);
         clear();
 }
References cell::current, HOLE, IN_MUD_W, IN_MUD_Y, cell::land, MUD, TIME, X, and Y.
Referenced by main().
read_land_states()
void read_land_states (FILE * stream_land, struct cell(*) board[X])
Definition at line 58 of file read_land_states.c.
 {
         char land_state;
         for (int i = 0; i < Y; i++) {
                 for (int j = 0; j < X; j++) {
                         land_state = fgetc(stream_land);
                         if (land_state == '3') {
                                 board[i][j].land = 3;
                         }
                         if (land_state == '4') {
                                 board[i][j].land = 4;
                         }
                         else if (land_state == '0') {
                                 board[i][j].land = 0;
                         }
                 }
         }
         fclose(stream_land);
 }
References X, and Y.
Referenced by start_game().
read_states()
void read_states (FILE * stream, struct cell board[Y][X])
Definition at line 59 of file read_states.c.
 {
         char state;
         for (int i = 0; i < Y; i++) {
                 for (int j = 0; j < X; j++) {
                         state = fgetc(stream);
                         if (state == '1') {
                                 board[i][j].current = 1;
                                 board[i][j].future = 1;
                         }
                         if (state == '2') {
                                 board[i][j].current = 2;
                                 board[i][j].future = 2;
                         }
                         if (state == '0') {
                                 board[i][j].current = 0;
                                 board[i][j].future = 0;
                         }
                 }
         }
         fclose(stream);
 }
References X, and Y.
Referenced by start_game().
save_file()
void save_file (struct cell board[Y][X])
Definition at line 58 of file save_game.c.
 {
         FILE *file_ptr = fopen(FILE_LIVES, "w");
         FILE *file_ptr_land = fopen(FILE_LAND, "w");
         for (int i = 0; i < Y; i++) {
                 for (int j = 0; j < X; j++) {
                         fprintf(file_ptr, "%d", board[i][j].current);
                         fprintf(file_ptr_land, "%d", board[i][j].land);
                 }
         }
         fclose(file_ptr);
         fclose(file_ptr_land);
 }
References cell::current, FILE_LAND, FILE_LIVES, cell::land, X, and Y.
Referenced by main().
start_game()
void start_game (struct cell board[Y][X])
Definition at line 58 of file start_game.c.
 {
         WINDOW * win = newwin(4, 27, 1, 20);
         refresh();
         box(win, '*', '*');
         int start;
         mvwprintw(win, 1, 1, "  press 1 for new game.");
         mvwprintw(win, 2, 1, "  press 2 to load game.");
         wrefresh(win);
         refresh();
         scanf("%d", &start);
         FILE *stream = fopen(FILE_LIVES, "r");
         FILE *stream_land = fopen(FILE_LAND, "r");
         switch (start) {
         case 1:
                 zero_the_boards(board);
                 first_board(board);
                 break;
         case 2:
                 if (stream) {
                         read_land_states(stream_land, board);
                         read_states(stream, board);
                 }
                 else if (stream == NULL) {
                         mvwprintw(win, 1, 1, " file not found starting a new game!!!");
                         wrefresh(win);
                         Sleep(TIME);
                         zero_the_boards(board);
                         first_board(board);
                 }
                 break;
         default:
                 break;
         }
 }
References FILE_LAND, FILE_LIVES, first_board(), read_land_states(), read_states(), TIME, and zero_the_boards().
Referenced by main().
zero_the_boards()
void zero_the_boards (struct cell board[Y][X])
Definition at line 59 of file zero.c.
 {
         for (int i = 0; i < Y; i++) {           /*nollaa current ja future*/
                 for (int j = 0; j < X; j++) {
                         board[i][j].current = 0;
                         board[i][j].future = 0;
                         board[i][j].land = 0;
                 }
         }
 }
References X, and Y.
Referenced by start_game().