GAME OF LIFE: start_game.c File Reference
start_game.c File Reference
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <Windows.h>
#include <ncurses.h>
#include "Header.h"
Functions
void start_game (struct cell board[Y][X])
Function Documentation
start_game()
void start_game (struct cell board[Y][X])
Definition at line 58 of file start_game.c.
 {
         WINDOW * win = newwin(4, 27, 1, 20);
         refresh();
         box(win, '*', '*');
         int start;
         mvwprintw(win, 1, 1, "  press 1 for new game.");
         mvwprintw(win, 2, 1, "  press 2 to load game.");
         wrefresh(win);
         refresh();
         scanf("%d", &start);
         FILE *stream = fopen(FILE_LIVES, "r");
         FILE *stream_land = fopen(FILE_LAND, "r");
         switch (start) {
         case 1:
                 zero_the_boards(board);
                 first_board(board);
                 break;
         case 2:
                 if (stream) {
                         read_land_states(stream_land, board);
                         read_states(stream, board);
                 }
                 else if (stream == NULL) {
                         mvwprintw(win, 1, 1, " file not found starting a new game!!!");
                         wrefresh(win);
                         Sleep(TIME);
                         zero_the_boards(board);
                         first_board(board);
                 }
                 break;
         default:
                 break;
         }
 }
References FILE_LAND, FILE_LIVES, first_board(), read_land_states(), read_states(), TIME, and zero_the_boards().
Referenced by main().